gram/urls.py
from django.contrib import admin
from django.urls import re_path,include
from django_registration.backends.one_step.views import RegistrationView
from django.contrib.auth import views as auth_views
from instagram import views 

app_name = "instagram"  

urlpatterns = [
   re_path('admin/', admin.site.urls),
   re_path('accounts/register/',
          RegistrationView.as_view(success_url='/'),
          name='django_registration_register'),
   re_path('accounts/', include('django_registration.backends.one_step.urls')),
   re_path('accounts/', include('django.contrib.auth.urls')),
   re_path('',include('instagram.urls')),
   re_path('logout/',auth_views.LogoutView.as_view(template_name = 'registration/login.html'), name = 'logout'),
   re_path('password-change/', auth_views.PasswordResetView.as_view(), name='password_change'),
]

instagram/urls.py
from django.urls import re_path, include
from . import views

app_name= 'instagram'

urlpatterns=[
    re_path('^$',views.index,name = 'homepage'),
    re_path("register", views.register_request, name="register"),
    re_path("login", views.login_request, name="login"),
    re_path("logout", views.logout_request, name= "logout"),
    re_path('profile/update/', views.update_profile, name='update.profile'),
    re_path('profile/', views.profile, name='profile'),     
    re_path('upload/add/', views.save_image, name='save.image'),
    re_path(r'^search/', views.search_results, name='search_results'),
]

instagram/models.py
from django.db import models
from cloudinary.models import CloudinaryField 
import datetime as dt
from django.contrib.auth.models import User


# Create your models here.
class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='images',default=0)
    image = CloudinaryField('image')
    image_name = models.CharField(max_length=50)
    image_caption = models.TextField()
    image_date = models.DateTimeField(auto_now_add=True)
    like_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    profile = models.ForeignKey(User, on_delete=models.CASCADE)   

    def save_image(self):
        self.save()

    def delete_image(self):
        self.delete()

    def update_caption(self, new_caption):
        self.image_caption = new_caption
        self.save()

    @classmethod
    def search_by_image_name(cls, search_term):
        images = cls.objects.filter(
            image_name__icontains=search_term)
        return images

    @classmethod
    def get_single_image(cls, id):
        image = cls.objects.get(id=id)
        return image

    def __str__(self):
        return self.image_name


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile_photo = CloudinaryField('image')
    bio = models.TextField(max_length=500, blank=True, null=True)
    contact = models.CharField(max_length=50, blank=True, null=True)

    def update(self):
        self.save()

    def save_profile(self):
        self.save()

    def delete_profile(self):
        self.delete()

    @classmethod
    def search_by_profile(cls, search_term):
        profile = cls.objects.filter(user__icontains=search_term)
        return profile

    def __str__(self):
        return self.user.username

class Likes(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    likes = models.BooleanField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.likes

class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def save_comment(self):
        self.save()

    def __str__(self):
        return self.comment

    class Meta:
        ordering = ['-comment_date']

class Follow(models.Model): 
    posted = models.DateTimeField(auto_now_add=True)
    followed = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='profile_followed')
    follower = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='profile_following')

    def __str__(self):
        return self.pk 

instagram/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile,Comments,Image

# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

instagram/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .models import  Image, Comments, Likes, Profile, User
from .forms import NewUserForm, UpdateProfileForm, UpdateUserForm
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordChangeView
import cloudinary
import cloudinary.uploader
import cloudinary.api


def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("main:homepage")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="django_registration/registration_form.html", context={"register_form":form})


def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("main:homepage")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="index.html", context={"login_form":form})


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return render(request, 'registration/login.html')


@login_required
def index(request):
    images = Image.objects.all().order_by('-image_date')
    return render(request, 'index.html', {'images': images})


@login_required
def profile(request):
  current_user = request.user
  images = Image.objects.filter(user_id = current_user.id).all()
  profile = Profile.objects.filter(user_id=current_user.id).first()
  
  return render(request,'profile.html',{"images":images,"profile":profile})


class PasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'users/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('users-home')

@login_required()
def update_profile(request):
    if request.method == 'POST':

        current_user = request.user

        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']

        bio = request.POST['bio']

        profile_image = request.FILES['profile_pic']
        profile_image = cloudinary.uploader.upload(profile_image)
        profile_url = profile_image['url']

        user = User.objects.get(id=current_user.id)

        # check if user exists in profile table and if not create a new profile
        if Profile.objects.filter(user_id=current_user.id).exists():

            profile = Profile.objects.get(user_id=current_user.id)
            profile.profile_photo = profile_url
            profile.bio = bio
            profile.save()
        else:
            profile = Profile(user_id=current_user.id,profile_photo=profile_url, bio=bio)
            profile.save_profile()

        user.first_name = first_name
        user.last_name = last_name
        user.username = username
        user.email = email

        user.save()

        return redirect('/profile', {'success': 'Profile Updated Successfully'})

        # return render(request, 'profile.html', {'success': 'Profile Updated Successfully'})
    else:
        return render(request, 'profile.html', {'danger': 'Profile Update Failed'})

@login_required()
def save_image(request):
    if request.method == 'POST':
        image_name = request.POST['image_name']
        image_caption = request.POST['image_caption']
        image_file = request.FILES['image_file']
        image_file = cloudinary.uploader.upload(image_file)
        image_url = image_file['url']
        image_public_id = image_file['public_id']
        image = Image(image_name=image_name, image_caption=image_caption, image=image_url,
                      profile_id=request.POST['user_id'], user_id=request.POST['user_id'])
        image.save_image()
        return redirect('/profile', {'success': 'Image Uploaded Successfully'})
        # return render(request, 'profile.html', {'success': 'Image Uploaded Successfully'})
    else:
        return render(request, 'profile.html', {'danger': 'Image Upload Failed'})



def search_results(request):
    if 'profile' in request.GET and request.GET["profile"]:
        search_term = request.GET.get("profile")
        searched_images = Profile.search_by_category(search_term)
        message = f"{search_term}"
    

        return render(request, 'search.html', {"message": message, "profiles": searched_images})

    else:
    
        message = "You haven't searched for any term"
        return render(request, 'search.html', {"message": message})

instagram/templates/base.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Instagram</title>
    {% endif %}

    {% block styles %}
    {% bootstrap_css %}
    <link rel="shortcut icon" type="image/png" href="/static/pics/Instagram-Icon.png"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endblock %}

</head>

<body>
    {% include "navbar.html" %}
    {% block content %}
    <h1>test</h1>
    {%endblock%}

    {% block scripts %}
    {% bootstrap_javascript %}
    {% endblock %}

    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
    </script>
</body>

</html>

instagram/templates/index.html
{% extends "base.html" %}
{% block content %}

<section class="feed-section">
    <div class="container posts mt-5">
        <div class="row">
            
            {% for image in images %}
            <div class="col-md-2 col-lg-2"></div>
            <div class="col-md-8 col-lg-8">
                <div class="card mb-4">
                    <div class="d-flex justify-content-start m-2">
                        <div>
                            <a href="">
                                <img src="/static/pics/Instagram-Icon.png" alt="" class="user-avatar border-radius"
                                    style="height:1.2cm; width:1,2cm;">
                            </a>
                        </div>
                        <div class="text-center mt-1">
                            <a href="">
                                <h6><small>{{ image.profile.user.username }} </small></h6>
                            </a>
                        </div>
                    </div>
                    <img src="{{ image.image.url }}" class="card-img-top" alt="Display Image">
                    <div class="card-body">
                        <small>
                            <div class="d-flex justify-content-start">
                                <div>
                                    <p>
                                        <a href=""> <i class="far fa-heart"></i></a>
                                    </p>
                                </div>
                                <div>
                                    <p>
                                        <a href=""> <i class="far fa-comment"></i></a>
                                    </p>
                                </div>
                            </div>
                        </small>
                        <a href="">
                            <p class="fade-item">{{image.like_count }} Likes <br>View All {{image.comment_count }}
                                Comments</p>
                            <h6 class="">{{ image.image_caption }}</h6>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-2"></div>
            {% endfor %}
        
        </div>
    </div>
</section>
{% endblock %}

instagram/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <div class="head">
            <a class="navbar-brand" href="#">Instagram</a>

            <div class="search-form"action="{% url 'instagram:search_results' %}" >
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                </form>
            </div>
        </div>

        <div class="navicons">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/"><i class="fa-solid fa-house"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/"><i
                            class="fa-solid fa-location-arrow"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#"><i class="fa-solid fa-square-plus"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/"><i class="fa-solid fa-compass"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/"><i class="fa-solid fa-heart"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'instagram:profile' %}"><i class="fa-solid fa-user"></i></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/logout"><i class="fa-solid fa-right-from-bracket"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Welcome, {{user.username}}</a>
                  </li>
                {% else %}

                <li class="nav-item">
                  <a class="nav-link" href="/login">Login</a>
                </li>
          
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

instagram/templates/profile.html
{% extends "base.html" %}
{% block content %}
<section class="profile container">
    <div class=" mt-5">
        <div class="row">
            <div class="col-md-4 col-lg-4">
                <div class="card profile-card">
                    {% if profile.profile_photo %}
                    <img src="{{profile.profile_photo.url}}" alt="" class="card-img-top">
                    {%else%}
                    <img src="/static/pics/user.png" class="card-img-top" alt="My profile picture">
                    {% endif %}
                    <div class="card-body text-center">
                        <h4 class="card-text">
                            {{ user.first_name }} {{ user.last_name }}
                        </h4>
                        <p>{{ user.username }}</p>
                        <p>
                            {% if profile.bio %}
                            <small>{{ profile.bio }}</small>
                            {% else %}
                            <span class="text-danger">No about me</span>
                            {% endif %}
                        </p>
                        <h6>Joined on: <span class="badge rounded-pill bg-secondary text-white">
                                {{ user.date_joined|date }} </span></h6>
                    </div>
                </div>
                <div class="row mt-3 mb-3">
                    <div class="col-md-12">
                        <div class="card p-2">
                            <button type="button" class="btn btn-lg m-3" data-bs-toggle="modal"
                                data-bs-target="#profileModal">
                                <i class="fa fa-plus text-white"></i> Update Profile
                            </button>
                            <div class="modal fade" id="profileModal" tabindex="-1" role="dialog"
                                aria-labelledby="profileModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="profileModalLabel">Update Profile</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{% url 'instagram:update.profile' %}" method="POST"
                                                enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="form-group mb-3">
                                                    <label for="name">First Name</label>
                                                    <input type="text" class="form-control" id="first_name"
                                                        name="first_name" value="{{ user.first_name }}">
                                                </div>
                                                <div class="form-group mb-3">
                                                    <label for="name">Last Name</label>
                                                    <input type="text" class="form-control" id="last_name"
                                                        name="last_name" value="{{ user.last_name }}">
                                                </div>
                                                <div class="form-group mb-3">
                                                    <label for="username">Username</label>
                                                    <input type="text" class="form-control" id="username"
                                                        name="username" value="{{ user.username }}">
                                                </div>
                                                <div class="form-group mb-3">
                                                    <label for="email">Email</label>
                                                    <input type="email" class="form-control" id="email" name="email"
                                                        value="{{ user.email}}">
                                                </div>
                                                <div class="form-group mb-3">
                                                    <label for="bio">Bio</label>
                                                    <textarea name="bio" id="bio" cols="30" rows="10"
                                                        class="form-control">{{ profile.bio }}</textarea>
                                                </div>
                                                <div class="form-group mb-3">
                                                    <label for="profile_pic">Profile Picture</label>
                                                    <input type="file" class="form-control" id="profile_pic"
                                                        name="profile_pic" required>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="submit" class="btn">Update Account</button>
                                                </div>
                                            </form>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-md-8 col-lg-8">
                <div class="row">
                    {% if success %}
                    <div class="alert alert-success" role="alert">
                        {{ success }}
                    </div>
                    {% elif danger %}
                    <div class="alert alert-danger" role="alert">
                        {{ danger }}
                    </div>
                    {% endif %}
                    <div class="col-md-12">
                        <button type="button" class="btn btn-lg m-3" data-bs-toggle="modal"
                            data-bs-target="#exampleModal">
                            <i class="fa fa-plus text-white"></i> Add Photo
                        </button>
                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Add Photo</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{% url 'instagram:save.image' %}" method="post"
                                            enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <label for="image_name">Name</label>
                                                <input type="text" class="form-control" value="" name="image_name"
                                                    required>
                                            </div>
                                            <input type="hidden" name="user_id" value="{{ user.id }}">
                                            <div class="form-group mt-3">
                                                <label for="exampleFormControlTextarea1">Caption</label>
                                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"
                                                    name="image_caption" required></textarea>
                                            </div>
                                            <div class="form-group mt-3">
                                                <label for="exampleFormControlFile1">Upload Photo</label>
                                                <input type="file" class="form-control" id="exampleFormControlFile1"
                                                    name="image_file" required>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn">Save</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                {% for image in images %}
                <div class="col-md-6">
                    <a href="">
                        <div class="card mb-4">
                            <img src="{{ image.image.url }}" class="card-img-tops" alt="Image">
                        </div>
                    </a>
                </div>
                {% empty %}

                <div class="col-md-6">
                    <div class="alert alert-info" role="alert">
                        No images!
                    </div>
                </div>
                {% endfor %}

            </div>

        </div>
    </div>
    </div>
</section>
{% endblock %}

instagram/templates/search.html
{% extends 'base.html' %}

{% block content %}

<style>
  .flex{
    display: flex;
  }
  .search{
    border-style: solid;
    border-color: lightgray;
    border-radius: 5px;
    border-width: thin;
  }
</style>

<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4 search">


        {% if profile %}
        <h6 class="text-center ">
          Profiles found
        </h6>
        {% for profile in profiles %}
      <div class="flex">
          <div>
            <a href="{% url  user.user.id  %}">
              <img src="{{user.profile.profile_pic}}" class="rounded-circle border" alt="img" width="50" height="50">
            </a>
          </div>
          <div>
            <p class="ml-2"><span class="font-weight-bold">{{user.user.username}}</span></p>
          </div>
        </div>
        {% endfor %}
        {% endif %}

        {% if images %}
          <h6 class="text-center">
            posts found
          </h6>
        {% for image in images %}
          <p>
            <a href="{% url 'allcomments' image_id=image.id %}" class="text-muted text-center">{{image.name}} </a>
          </p>
        {% endfor %}

        {% endif %}


    </div>
    <div class="col-md-4"></div>
  </div>
</div>



{% endblock %}